# Generated by Django 2.1.7 on 2019-03-27 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titled', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked-out', 'Checked Out')], default='available', max_length=32)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_borrowed', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
