# Generated by Django 2.1.7 on 2019-03-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titled',
            new_name='title',
        ),
    ]
